### ISSUE TITLE
platoon vehicles leave the network will return error

### ISSUE THREAD

**Issue by zhaotuo0815** [michele-segata/plexe-pyapi#12]
<img width="599" alt="error" src="https://user-images.githubusercontent.com/59630993/181173917-cc686166-e38c-46af-9644-b9857be641a1.png">
<img width="960" alt="platoon" src="https://user-images.githubusercontent.com/59630993/181173927-df37af51-68ca-4f38-86c2-45cf85fbae4f.png">
Hello developer, when the platoon vehicles I generate is going to leave the road network, it will report an error(as shown in the photo), but the simulation time has not reached the final simulation time I set.

**Comment by michele-segata** [comment]
The problem here might be that, when the leader of a platoon leaves the scenario, the other vehicles cannot find it anymore. As there is no network simulator in the Plexe Python APIs, communication is simply done by copying information of some specific vehicles to some other ones (e.g., passing leader speed and acceleration to all the followers). In the braking scenario, this is [done here](https://github.com/michele-segata/plexe-pyapi/blob/112848c20eb84da82efd87e771df350c7b266c09/examples/brakedemo.py#L111). Inside the `communicate` method, the code fetches data about vehicles from SUMO (e.g., [here](https://github.com/michele-segata/plexe-pyapi/blob/112848c20eb84da82efd87e771df350c7b266c09/examples/utils.py#L123)). I fear that, if the vehicle leaves the simulation and you try to fetch data about that, SUMO might crash.
A solution in this case would be to first check whether a vehicle exist and fetch data about that only if it is found. You could use the [getIDList](https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html) TraCI method for that.

**Comment by zhaotuo0815** [comment]
Thank you very much for your reply, I will try it according to your method.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "michele-segata/plexe-pyapi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [michele-segata/plexe-pyapi] platoon vehicles leave the network will return error (Issue #12)





 
The problem here might be that, when the leader of a platoon leaves the scenario, the other vehicles cannot find it anymore. As there is no network simulator in the Plexe Python APIs, communication is simply done by copying information of some specific vehicles to some other ones (e.g., passing leader speed and acceleration to all the followers). In the braking scenario, this is done here. Inside the communicate method, the code fetches data about vehicles from SUMO (e.g., here). I fear that, if the vehicle leaves the simulation and you try to fetch data about that, SUMO might crash.
 A solution in this case would be to first check whether a vehicle exist and fetch data about that only if it is found. You could use the getIDList TraCI method for that.
