### ISSUE TITLE
How can I download plexe?

### ISSUE THREAD

**Issue by xhy12345x** [michele-segata/plexe-pyapi#18]

**Comment by michele-segata** [comment]
Please visit the documentation on the website: [plexe.car2x.org](http://plexe.car2x.org)

**Comment by xhy12345x** [comment]
Hello, I found that most of the plexes are on the linux or mac system. I want to ask you how to install plexe in the window system.
Thanks again! Have
&nbsp;a good day.





3447386862
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "michele-segata/plexe-pyapi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月25日(星期三) 晚上10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [michele-segata/plexe-pyapi] How can I download plexe? (Issue #18)





 
Closed #18 as completed.

**Comment by michele-segata** [comment]
Plexe better works on Unix-base systems. For the best performance, you might want to install Ubuntu linux alongside your Windows installation. Otherwise, you can either use the InstantPlexe virtual machine image (but the performance is rather limited) or build the simulator for Windows as indicated in the instructions.
However, given that you are writing in the issues of the Python API repository, I assume you do not need to simulate the network with Veins and OMNeT++. In such case, simply download the SUMO Windows binaries and use the APIs in this repository as indicated in the README. That should work out of the box.

**Comment by MrEdwardiop** [comment]
Hello, another question please, can I use Veins, OMNeT++, and SUMO to simulate Vehicular Ad hoc Networks (VANETs) in a Windows environment? or I should develop my project under Ubuntu? Thanks~

**Comment by michele-segata** [comment]
It should work on Windows as well, but I can't provide support for that.
